name: Booking master component

on:
  push:
    tags:
      - booking-master-component-v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/booking-master-component.yml
      - kubernetes/components/booking-master/**

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  WASH_VERSION: "0.39.0"
  WASM_TOOLS_VERSION: "1.239.0"

jobs:
  booking-master-build:
    permissions:
      contents: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Fetch Rust build cache
        uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5
        with:
          path: |
            kubernetes/components/booking-master/target/
          key: cargo-${{ hashFiles('kubernetes/components/booking-master/Cargo.lock') }}
      - name: Install devbox
        uses: jetify-com/devbox-install-action@a0d2d53632934ae004f878c840055956d9f741b0 # v0.14.0
        with:
          project-path: ./kubernetes/components/booking-master
          enable-cache: "true"
          devbox-version: 0.16.0
      - name: Build component
        working-directory: kubernetes/components/booking-master
        run: devbox run build
      - name: Save Rust build cache
        uses: actions/cache/save@9255dc7a253b0ccc959486e2bca901246202afeb # v5
        with:
          path: |
            kubernetes/components/booking-master/target/
          key: cargo-${{ hashFiles('kubernetes/components/booking-master/Cargo.lock') }}
      - name: Upload artifact for publish step
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        if: ${{ startswith(github.ref, 'refs/tags/booking-master-component-v') }}
        with:
          name: booking-master-component
          path: kubernetes/components/booking-master/build/booking_master_s.wasm

  booking-master-publish:
    runs-on: ubuntu-24.04
    needs: [booking-master-build]
    if: ${{ startswith(github.ref, 'refs/tags/booking-master-component-v') }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - name: Determine version
        id: meta
        shell: bash
        env:
          REF: ${{ github.ref }}
          REF_PREFIX: "refs/tags/booking-master-component-v"
        run: |
          export VERSION=${REF#$REF_PREFIX};
          echo -e "version=${VERSION}" >> $GITHUB_OUTPUT;
      - name: Download artifact from build step
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131
        with:
          path: kubernetes/components/booking-master/artifacts
      - name: Install wash
        uses: taiki-e/install-action@00a367b59ffa7299659baf1168279aefe69f5516 # v2.62.10
        with:
          tool: ${{ format('wash@{0},wasm-tools@{1}', env.WASH_VERSION, env.WASM_TOOLS_VERSION) }}
      - name: Push version-tagged WebAssembly binary to GHCR
        env:
          WASH_REG_USER: ${{ github.repository_owner }}
          WASH_REG_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        working-directory: kubernetes/components/booking-master
        run: |
          wash push ghcr.io/${{ github.repository_owner }}/wasmcloud-tutorial/booking-master:${{ steps.meta.outputs.version }} artifacts/booking_master_s.wasm
